In [2]:
!pip install tensorflow==2.9.1 tensorflow-gpu==2.9.1 tensorflow-hub opencv-python matplotlib

In [3]:
# Import TF and TF Hub libraries.
import tensorflow as tf
import tensorflow_hub as hub
import numpy as np
from matplotlib import pyplot as plt
import cv2
import math

# Download the model from TF Hub.
model = hub.load("https://tfhub.dev/google/movenet/multipose/lightning/1")
movenet = model.signatures['serving_default']

In [50]:
def draw_keypoints(frame, keypoints, confidence_threshold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
    for kp in shaped:
        ky, kx, kp_conf = kp
        if kp_conf > confidence_threshold:
            cv2.circle(frame, (int(kx), int(ky)), 6, (0,255,0), -1)
    cv2.circle(frame, (int(shaped[0][1]), int(shaped[0][0])), 4, (255,0,0), -1) #Nose

In [51]:
EDGES = {
    (0, 1): 'm',
    (0, 2): 'c',
    (1, 3): 'm',
    (2, 4): 'c',
    (0, 5): 'm',
    (0, 6): 'c',
    (5, 7): 'm',
    (7, 9): 'm',
    (6, 8): 'c',
    (8, 10): 'c',
    (5, 6): 'y',
    (5, 11): 'm',
    (6, 12): 'c',
    (11, 12): 'y',
    (11, 13): 'm',
    (13, 15): 'm',
    (12, 14): 'c',
    (14, 16): 'c'
}

def draw_connections(frame, keypoints, edges, confidence_threshold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
    for edge, color in edges.items():
        p1, p2 = edge
        y1, x1, c1 = shaped[p1]
        y2, x2, c2 = shaped[p2]
        
        if (c1 > confidence_threshold) & (c2 > confidence_threshold):      
            cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0,0,255), 4)

In [55]:
def draw_head_direction(frame, keypoints, edges, confidence_threshold):
    y, x, c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints, [y,x,1]))
    
    confident_booster = 0.2
    c1 = shaped[3][2] + confident_booster
    c2 = shaped[4][2] + confident_booster
    
    if (c1 > confidence_threshold) & (c2 > confidence_threshold):      
        middle_eartoear = (shaped[4] + shaped[3])/2
        cv2.arrowedLine(frame, (int(middle_eartoear[1]), int(middle_eartoear[0])), (int(shaped[0][1]), int(shaped[0][0])), (0,0,255), 2)

In [44]:
y, x, c = frame.shape
shaped = np.squeeze(np.multiply(keypoints_with_scores, [y,x,1]))
print(shaped[1])
print(shaped[1][3][2])

[[2.75933819e+02 3.22141418e+02 6.11229420e-01]
 [2.53419371e+02 3.40900993e+02 6.89024568e-01]
 [2.54599171e+02 3.07091522e+02 5.90774596e-01]
 [2.66134129e+02 3.70744553e+02 5.32036364e-01]
 [2.72657433e+02 2.90947762e+02 5.16564190e-01]
 [3.71758661e+02 4.22541008e+02 4.74491775e-01]
 [3.81323948e+02 2.44224682e+02 3.56154084e-01]
 [4.66409798e+02 4.49940147e+02 5.80690838e-02]
 [4.67604189e+02 2.22019424e+02 6.30560294e-02]
 [4.62755470e+02 4.28747978e+02 6.35173097e-02]
 [4.62302284e+02 2.72095737e+02 3.03999316e-02]
 [4.73508568e+02 3.76105080e+02 3.74675961e-04]
 [4.68062296e+02 3.01030025e+02 5.91709337e-04]
 [4.18588314e+02 4.00367088e+02 7.51273567e-03]
 [4.44145746e+02 2.38210430e+02 3.01764719e-02]
 [3.33366280e+02 3.09954929e+02 3.62741470e-04]
 [3.45622387e+02 3.34943199e+02 1.38345873e-02]]
0.5320363640785217


In [58]:
# Function to loop through each person detected and render
def loop_through_people(frame, keypoints_with_scores, edges, confidence_threshold):
    for person in keypoints_with_scores:
        #draw_connections(frame, person, edges, confidence_threshold)
        #draw_keypoints(frame, person, confidence_threshold)
        draw_head_direction(frame, person, edges, confidence_threshold)

In [61]:
cap = cv2.VideoCapture('test001.mp4')
while cap.isOpened():
    ret, frame = cap.read()
    
    # Resize image
    img = frame.copy()
    img = tf.image.resize_with_pad(tf.expand_dims(img, axis=0), 384,640)
    input_img = tf.cast(img, dtype=tf.int32)
    
    # Detection section
    results = movenet(input_img)
    keypoints_with_scores = results['output_0'].numpy()[:,:,:51].reshape((6,17,3))
    
    # Render keypoints 
    loop_through_people(frame, keypoints_with_scores, EDGES, 0.4)
    
    cv2.imshow('Movenet Multipose', frame)
    
    if cv2.waitKey(10) & 0xFF==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()